name: pytest

on:
    push:

jobs:
    pytest:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'
            #cache: 'hatch'
        - name: Install dependencies
          run: | 
            python -m pip install hatch --upgrade pip
            hatch env create test
        - name: Lint with Ruff
          run: hatch run ruff check --output-format=github .
          #continue-on-error: true
        - name: Setup cmake
          uses: jwlawson/actions-setup-cmake@v2
        - name: Get pybind11 CMake directory
          id: pybind11_dir
          run: echo "dir=$(hatch run test:python -m pybind11 --cmakedir)" >> $GITHUB_OUTPUT
        - name: Set CMAKE_PREFIX_PATH
          run: echo "CMAKE_PREFIX_PATH=${{ steps.pybind11_dir.outputs.dir }}" >> $GITHUB_ENV
        - name: Run pytest
          run: hatch run test:pytest
        #- name: Upload pytest test results
        #  uses: actions/upload-artifact@v4
        #  with:
        #    name: pytest-results-${{ matrix.python-version }}
        #    path: junit/test-results-${{ matrix.python-version }}.xml
        #  # Use always() to always run this step to publish test results when there are test failures
        #  if: ${{ always() }}
